package org.sma.jpa.repository.fee;

import org.sma.jpa.model.fee.FeeCategory;
import org.sma.jpa.model.fee.StudentFeeAllocation;
import org.sma.jpa.model.school.AcademicYear;
import org.sma.jpa.model.school.SchoolProfile;
import org.sma.jpa.model.studentmgmt.StudentProfile;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * Repository for StudentFeeAllocation entity
 */
@Repository
public interface StudentFeeAllocationRepository extends JpaRepository<StudentFeeAllocation, Long> {
    
    /**
     * Find all fee allocations for a student in an academic year
     */
    List<StudentFeeAllocation> findByStudentAndAcademicYear(StudentProfile student, AcademicYear academicYear);
    
    /**
     * Find fee allocations by status
     */
    List<StudentFeeAllocation> findBySchoolAndAcademicYearAndAllocationStatus(
        SchoolProfile school, AcademicYear academicYear, String allocationStatus);
    
    /**
     * Find fee allocations by student and status
     */
    List<StudentFeeAllocation> findByStudentAndAllocationStatus(StudentProfile student, String allocationStatus);
    
    /**
     * Find fee allocations by category
     */
    List<StudentFeeAllocation> findBySchoolAndAcademicYearAndFeeCategory(
        SchoolProfile school, AcademicYear academicYear, FeeCategory feeCategory);
    
    /**
     * Find fee allocations for a specific month
     */
    List<StudentFeeAllocation> findBySchoolAndAcademicYearAndApplicableMonth(
        SchoolProfile school, AcademicYear academicYear, String month);
    
    /**
     * Find overdue fee allocations
     */
    @Query("SELECT sfa FROM StudentFeeAllocation sfa WHERE sfa.school = :school " +
           "AND sfa.academicYear = :academicYear " +
           "AND sfa.allocationStatus IN ('PENDING', 'PARTIALLY_PAID') " +
           "AND sfa.dueDate < :currentDate")
    List<StudentFeeAllocation> findOverdueFees(
        @Param("school") SchoolProfile school,
        @Param("academicYear") AcademicYear academicYear,
        @Param("currentDate") LocalDate currentDate);
    
    /**
     * Find fee allocation by unique code
     */
    Optional<StudentFeeAllocation> findByAllocationCode(String allocationCode);
    
    /**
     * Find fee allocations due within a date range
     */
    @Query("SELECT sfa FROM StudentFeeAllocation sfa WHERE sfa.school = :school " +
           "AND sfa.academicYear = :academicYear " +
           "AND sfa.dueDate BETWEEN :startDate AND :endDate " +
           "AND sfa.allocationStatus IN ('PENDING', 'PARTIALLY_PAID')")
    List<StudentFeeAllocation> findFeesComingDue(
        @Param("school") SchoolProfile school,
        @Param("academicYear") AcademicYear academicYear,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate);
    
    /**
     * Calculate total pending amount for a student
     */
    @Query("SELECT COALESCE(SUM(sfa.pendingAmount), 0) FROM StudentFeeAllocation sfa " +
           "WHERE sfa.student = :student " +
           "AND sfa.academicYear = :academicYear " +
           "AND sfa.allocationStatus IN ('PENDING', 'PARTIALLY_PAID')")
    java.math.BigDecimal calculateTotalPendingAmount(
        @Param("student") StudentProfile student,
        @Param("academicYear") AcademicYear academicYear);
    
    /**
     * Find manual allocations (non-auto-generated)
     */
    List<StudentFeeAllocation> findBySchoolAndAcademicYearAndAutoGeneratedFalse(
        SchoolProfile school, AcademicYear academicYear);
}
