// Fee Category Models
export interface FeeCategoryRequest {
  categoryCode: string;
  categoryName: string;
  categoryType: string;
  isMandatory: boolean;
  isRefundable: boolean;
  displayOrder?: number;
  description?: string;
  feeApplicability: string;
  paymentFrequency: string;
}

export interface FeeCategoryResponse {
  id: string;
  categoryCode: string;
  categoryName: string;
  categoryType: string;
  isMandatory: boolean;
  isRefundable: boolean;
  displayOrder?: number;
  description?: string;
  isActive: boolean;
  createdDate: string;
  feeApplicability?: string;
  paymentFrequency?: string;
}

// Student Fee Allocation Models
export interface StudentFeeAllocationRequest {
  studentId: number;
  feeCategoryId: string;
  feeStructureId?: string;
  feeAmount: number;
  durationType: string;
  applicableMonth?: string;
  quarter?: string;
  dueDate: string;
  paymentDeadline?: string;
  isMandatory: boolean;
  discountAmount?: number;
  discountReason?: string;
  remarks?: string;
}

export interface StudentFeeAllocationResponse {
  id: string;
  allocationCode: string;
  studentId: number;
  studentName: string;
  studentRollNumber: string;
  feeCategoryId: string;
  feeCategoryName: string;
  feeCategoryType: string;
  feeStructureId?: string;
  feeStructureName?: string;
  feeAmount: number;
  durationType: string;
  applicableMonth?: string;
  quarter?: string;
  dueDate: string;
  allocationDate: string;
  allocationStatus: string;
  paidAmount: number;
  pendingAmount: number;
  discountAmount: number;
  discountReason?: string;
  lateFeeAmount: number;
  lateFeeAppliedDate?: string;
  paymentDeadline?: string;
  isMandatory: boolean;
  autoGenerated: boolean;
  remarks?: string;
  academicYear: string;
  createdDate: string;
}
