// Fee Category Models
export interface FeeCategoryRequest {
  categoryCode: string;
  categoryName: string;
  categoryType: string;
  isMandatory: boolean;
  isRefundable: boolean;
  displayOrder?: number;
  description?: string;
  feeApplicability: string;
  paymentFrequency: string;
  status?: string;
}

export interface FeeCategoryResponse {
  id: string;
  categoryCode: string;
  categoryName: string;
  categoryType: string;
  isMandatory: boolean;
  isRefundable: boolean;
  displayOrder?: number;
  description?: string;
  status: string;
  createdDate: string;
  feeApplicability?: string;
  paymentFrequency?: string;
}

// Fee Plan Models
export interface InstallmentDetail {
  installmentNo: number;
  installmentName: string;
  periodStartDate: string;
  periodEndDate: string;
  amountDue: number;
  dueDate: string;
}

export interface FeePlanRequest {
  academicYearId: number;
  categoryId: number;
  totalAmount: number;
  frequency: string;
  installmentsCount: number;
  status?: string;
  installments: InstallmentDetail[];
}

export interface InstallmentResponse {
  id: number;
  installmentNo: number;
  installmentName: string;
  periodStartDate: string;
  periodEndDate: string;
  amountDue: number;
  dueDate: string;
  status: string;
}

export interface FeePlanResponse {
  id: number;
  academicYearId: number;
  academicYearName: string;
  categoryId: number;
  categoryName: string;
  totalAmount: number;
  frequency: string;
  installmentsCount: number;
  status: string;
  createdDate: string;
  installments?: InstallmentResponse[];
}

export interface StudentFeeAllocationResponse {
  id: string;
  allocationCode: string;
  studentId: number;
  studentName: string;
  studentRollNumber: string;
  feeCategoryId: string;
  feeCategoryName: string;
  feeCategoryType: string;
  feeStructureId?: string;
  feeStructureName?: string;
  feeAmount: number;
  durationType: string;
  applicableMonth?: string;
  quarter?: string;
  dueDate: string;
  allocationDate: string;
  allocationStatus: string;
  paidAmount: number;
  pendingAmount: number;
  discountAmount: number;
  discountReason?: string;
  lateFeeAmount: number;
  lateFeeAppliedDate?: string;
  paymentDeadline?: string;
  isMandatory: boolean;
  autoGenerated: boolean;
  remarks?: string;
  academicYear: string;
  createdDate: string;
}

// Student Fee Payment Models
export interface StudentFeePaymentRequest {
  studentId: number;
  feeInstallmentId: number;
  amountPaid: number;
  discountAmount?: number;
  paidOn: string; // ISO date string
  paymentRef?: string;
  remarks?: string;
}

export interface StudentFeePaymentResponse {
  id: number;
  schoolId: number;
  studentId: number;
  studentName: string;
  feeInstallmentId: number;
  installmentName: string;
  amountPaid: number;
  discountAmount: number;
  paidOn: string;
  paymentRef?: string;
  remarks?: string;
}

// Pending Payment Models
export interface PendingPaymentResponse {
  studentId: number;
  studentName: string;
  admissionNo: string;
  rollNumber: string;
  className: string;
  sectionName: string;
  feeInstallmentId: number;
  installmentName: string;
  feeCategoryName: string;
  amountDue: number;
  dueDate: string;
  daysPastDue: number;
}
