package org.sma.jpa.model.fee;

import org.sma.jpa.model.BaseEntity;
import org.sma.jpa.model.school.SchoolProfile;
import org.sma.jpa.model.school.AcademicYear;
import org.sma.jpa.model.studentmgmt.StudentProfile;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity for Student Fee Allocation - Manual fee assignment to specific students
 * Admin can assign fees based on category, duration, and month
 */
@Entity
@Table(name = "student_fee_allocation", schema = "sma_admin",
    indexes = {
        @Index(name = "idx_sfa_student", columnList = "student_id"),
        @Index(name = "idx_sfa_school_year", columnList = "school_id, academic_year_id"),
        @Index(name = "idx_sfa_category", columnList = "fee_category_id"),
        @Index(name = "idx_sfa_status", columnList = "allocation_status"),
        @Index(name = "idx_sfa_due_date", columnList = "due_date")
    })
public class StudentFeeAllocation extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "school_id", nullable = false)
    private SchoolProfile school;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "academic_year_id", nullable = false)
    private AcademicYear academicYear;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    private StudentProfile student;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fee_category_id", nullable = false)
    private FeeCategory feeCategory;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fee_structure_id")
    private FeeStructure feeStructure;

    @Column(name = "allocation_code", nullable = false, unique = true, length = 50)
    private String allocationCode; // Unique code: SFA-2024-001

    @Column(name = "fee_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal feeAmount;

    @Column(name = "duration_type", length = 20)
    private String durationType; // MONTHLY, QUARTERLY, HALF_YEARLY, ANNUAL, ONE_TIME

    @Column(name = "applicable_month", length = 10)
    private String applicableMonth; // JANUARY, FEBRUARY, etc., or null for non-monthly

    @Column(name = "quarter", length = 10)
    private String quarter; // Q1, Q2, Q3, Q4 for quarterly

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Column(name = "allocation_date", nullable = false)
    private LocalDate allocationDate;

    @Column(name = "allocation_status", nullable = false, length = 20)
    private String allocationStatus; // PENDING, PAID, PARTIALLY_PAID, OVERDUE, WAIVED, CANCELLED

    @Column(name = "paid_amount", precision = 10, scale = 2)
    private BigDecimal paidAmount = BigDecimal.ZERO;

    @Column(name = "pending_amount", precision = 10, scale = 2)
    private BigDecimal pendingAmount;

    @Column(name = "discount_amount", precision = 10, scale = 2)
    private BigDecimal discountAmount = BigDecimal.ZERO;

    @Column(name = "discount_reason", length = 300)
    private String discountReason;

    @Column(name = "late_fee_amount", precision = 10, scale = 2)
    private BigDecimal lateFeeAmount = BigDecimal.ZERO;

    @Column(name = "late_fee_applied_date")
    private LocalDate lateFeeAppliedDate;

    @Column(name = "payment_deadline")
    private LocalDate paymentDeadline;

    @Column(name = "is_mandatory", nullable = false)
    private Boolean isMandatory = true;

    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = false; // false for manual allocation

    @Column(name = "remarks", length = 500)
    private String remarks;

    @Column(name = "allocated_by")
    private Long allocatedBy; // Staff/Admin ID who allocated

    // Getters and Setters
    public SchoolProfile getSchool() {
        return school;
    }

    public void setSchool(SchoolProfile school) {
        this.school = school;
    }

    public AcademicYear getAcademicYear() {
        return academicYear;
    }

    public void setAcademicYear(AcademicYear academicYear) {
        this.academicYear = academicYear;
    }

    public StudentProfile getStudent() {
        return student;
    }

    public void setStudent(StudentProfile student) {
        this.student = student;
    }

    public FeeCategory getFeeCategory() {
        return feeCategory;
    }

    public void setFeeCategory(FeeCategory feeCategory) {
        this.feeCategory = feeCategory;
    }

    public FeeStructure getFeeStructure() {
        return feeStructure;
    }

    public void setFeeStructure(FeeStructure feeStructure) {
        this.feeStructure = feeStructure;
    }

    public String getAllocationCode() {
        return allocationCode;
    }

    public void setAllocationCode(String allocationCode) {
        this.allocationCode = allocationCode;
    }

    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    public String getDurationType() {
        return durationType;
    }

    public void setDurationType(String durationType) {
        this.durationType = durationType;
    }

    public String getApplicableMonth() {
        return applicableMonth;
    }

    public void setApplicableMonth(String applicableMonth) {
        this.applicableMonth = applicableMonth;
    }

    public String getQuarter() {
        return quarter;
    }

    public void setQuarter(String quarter) {
        this.quarter = quarter;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public LocalDate getAllocationDate() {
        return allocationDate;
    }

    public void setAllocationDate(LocalDate allocationDate) {
        this.allocationDate = allocationDate;
    }

    public String getAllocationStatus() {
        return allocationStatus;
    }

    public void setAllocationStatus(String allocationStatus) {
        this.allocationStatus = allocationStatus;
    }

    public BigDecimal getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(BigDecimal paidAmount) {
        this.paidAmount = paidAmount;
    }

    public BigDecimal getPendingAmount() {
        return pendingAmount;
    }

    public void setPendingAmount(BigDecimal pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    public String getDiscountReason() {
        return discountReason;
    }

    public void setDiscountReason(String discountReason) {
        this.discountReason = discountReason;
    }

    public BigDecimal getLateFeeAmount() {
        return lateFeeAmount;
    }

    public void setLateFeeAmount(BigDecimal lateFeeAmount) {
        this.lateFeeAmount = lateFeeAmount;
    }

    public LocalDate getLateFeeAppliedDate() {
        return lateFeeAppliedDate;
    }

    public void setLateFeeAppliedDate(LocalDate lateFeeAppliedDate) {
        this.lateFeeAppliedDate = lateFeeAppliedDate;
    }

    public LocalDate getPaymentDeadline() {
        return paymentDeadline;
    }

    public void setPaymentDeadline(LocalDate paymentDeadline) {
        this.paymentDeadline = paymentDeadline;
    }

    public Boolean getIsMandatory() {
        return isMandatory;
    }

    public void setIsMandatory(Boolean isMandatory) {
        this.isMandatory = isMandatory;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Long getAllocatedBy() {
        return allocatedBy;
    }

    public void setAllocatedBy(Long allocatedBy) {
        this.allocatedBy = allocatedBy;
    }
}
